module.exports = {
"q": {distance: 1, hand: "sol", finger: "serce"},
"w": {distance: 1, hand: "sol", finger: "yuzuk"},
"e": {distance: 1, hand: "sol", finger: "orta"},
"r": {distance: 1, hand: "sol", finger: "isaret"},
"t": {distance: 2, hand: "sol", finger: "isaret"},
"y": {distance: 2, hand: "sag", finger: "isaret"},
"u": {distance: 1, hand: "sag", finger: "isaret"},
"i": {distance: 1, hand: "sag", finger: "orta"},
"o": {distance: 1, hand: "sag", finger: "yuzuk"},
"p": {distance: 1, hand: "sag", finger: "serce"},
"a": {distance: 0, hand: "sol", finger: "serce"},
"s": {distance: 0, hand: "sol", finger: "yuzuk"},
"d": {distance: 0, hand: "sol", finger: "orta"},
"f": {distance: 0, hand: "sol", finger: "isaret"},
"g": {distance: 1, hand: "sol", finger: "isaret"},
"h": {distance: 1, hand: "sag", finger: "isaret"},
"j": {distance: 0, hand: "sag", finger: "isaret"},
"k": {distance: 0, hand: "sag", finger: "orta"},
"l": {distance: 0, hand: "sag", finger: "yuzuk"},
";": {distance: 0, hand: "sag", finger: "serce"},
"z": {distance: 1, hand: "sol", finger: "serce"},
"x": {distance: 1, hand: "sol", finger: "yuzuk"},
"c": {distance: 1, hand: "sol", finger: "orta"},
"v": {distance: 1, hand: "sol", finger: "isaret"},
"b": {distance: 2, hand: "sol", finger: "isaret"},
"n": {distance: 2, hand: "sag", finger: "isaret"},
"m": {distance: 1, hand: "sag", finger: "isaret"},
",": {distance: 1, hand: "sag", finger: "orta"},
".": {distance: 1, hand: "sag", finger: "yuzuk"},
"/": {distance: 1, hand: "sag", finger: "serce"},
" ": null,
};
