registerLayout("f-turkish", {
"f": {distance: 1, hand: "sol", finger: "pinky"},
"g": {distance: 1, hand: "sol", finger: "ring"},
"ğ": {distance: 1, hand: "sol", finger: "middle"},
"ı": {distance: 1, hand: "sol", finger: "index"},
"o": {distance: 2, hand: "sol", finger: "index"},
"d": {distance: 2, hand: "sag", finger: "index"},

"r": {distance: 1, hand: "sag", finger: "index"},
"n": {distance: 1, hand: "sag", finger: "middle"},
"h": {distance: 1, hand: "sag", finger: "ring"},
"p": {distance: 1, hand: "sag", finger: "pinky"},
"q": {distance: 2, hand: "sag", finger: "pinky"},

"w": {distance: 3, hand: "sag", finger: "pinky"},
"u": {distance: 0, hand: "sol", finger: "pinky"},
"i": {distance: 0, hand: "sol", finger: "ring"},
"e": {distance: 0, hand: "sol", finger: "middle"},
"a": {distance: 0, hand: "sol", finger: "index"},
"ü": {distance: 1, hand: "sol", finger: "index"},

"t": {distance: 1, hand: "sag", finger: "index"},
"k": {distance: 0, hand: "sag", finger: "index"},
"m": {distance: 0, hand: "sag", finger: "middle"},
"l": {distance: 0, hand: "sag", finger: "ring"},
"y": {distance: 0, hand: "sag", finger: "pinky"},
"ş": {distance: 1, hand: "sag", finger: "pinky"},

"x": {distance: 2, hand: "sag", finger: "pinky"},
"j": {distance: 1, hand: "sol", finger: "pinky"},
"ö": {distance: 1, hand: "sol", finger: "ring"},
"v": {distance: 1, hand: "sol", finger: "middle"},
"c": {distance: 1, hand: "sol", finger: "index"},
"ç": {distance: 2, hand: "sol", finger: "index"},

"z": {distance: 2, hand: "sag", finger: "index"},
"s": {distance: 1, hand: "sag", finger: "index"},
"b": {distance: 1, hand: "sag", finger: "middle"},
//",": {distance: 1, hand: "sag", finger: "ring"},
//".": {distance: 1, hand: "sag", finger: "pinky"},
}, false);
