module.exports = {
"f": {distance: 1, hand: "sol", finger: "serce"},
"g": {distance: 1, hand: "sol", finger: "yuzuk"},
"ğ": {distance: 1, hand: "sol", finger: "orta"},
"ı": {distance: 1, hand: "sol", finger: "isaret"},
"o": {distance: 2, hand: "sol", finger: "isaret"},
"d": {distance: 2, hand: "sag", finger: "isaret"},
"r": {distance: 1, hand: "sag", finger: "isaret"},
"n": {distance: 1, hand: "sag", finger: "orta"},
"h": {distance: 1, hand: "sag", finger: "yuzuk"},
"p": {distance: 1, hand: "sag", finger: "serce"},
"q": {distance: 2, hand: "sag", finger: "serce"},
"w": {distance: 3, hand: "sag", finger: "serce"},
"u": {distance: 0, hand: "sol", finger: "serce"},
"i": {distance: 0, hand: "sol", finger: "yuzuk"},
"e": {distance: 0, hand: "sol", finger: "orta"},
"a": {distance: 0, hand: "sol", finger: "isaret"},
"ü": {distance: 1, hand: "sol", finger: "isaret"},
"t": {distance: 1, hand: "sag", finger: "isaret"},
"k": {distance: 0, hand: "sag", finger: "isaret"},
"m": {distance: 0, hand: "sag", finger: "orta"},
"l": {distance: 0, hand: "sag", finger: "yuzuk"},
"y": {distance: 0, hand: "sag", finger: "serce"},
"ş": {distance: 1, hand: "sag", finger: "serce"},
"x": {distance: 2, hand: "sag", finger: "serce"},
"j": {distance: 1, hand: "sol", finger: "serce"},
"ö": {distance: 1, hand: "sol", finger: "yuzuk"},
"v": {distance: 1, hand: "sol", finger: "orta"},
"c": {distance: 1, hand: "sol", finger: "isaret"},
"ç": {distance: 2, hand: "sol", finger: "isaret"},
"z": {distance: 2, hand: "sag", finger: "isaret"},
"s": {distance: 1, hand: "sag", finger: "isaret"},
"b": {distance: 1, hand: "sag", finger: "orta"},
",": {distance: 1, hand: "sag", finger: "yuzuk"},
".": {distance: 1, hand: "sag", finger: "serce"},
" ": null,
};
